name: mlapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.0
  google_generative_ai: ^0.4.6
  google_mlkit_text_recognition: ^0.11.0
  http: ^1.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  provider: ^6.1.2
  share_plus: ^10.1.2
  speech_to_text: ^6.6.1
  translator: ^1.0.3+1
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdfviewer: ^27.2.3
  device_info_plus: ^10.1.2
  intl: ^0.19.0
  flutter_markdown: ^0.7.4+2
  shared_preferences: ^2.3.3
  deepgram_speech_to_text: ^2.3.2
  just_audio: ^0.9.42
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-VariableFont_wght.ttf
